### PR TITLE
Update CI workspace and fixes testing cases

### PR DESCRIPTION
**Pull request by guangbochen**
**Problem:**
1. https://github.com/rancher/helm/pull/13#issuecomment-457274887 CI/CD build is failed because of incorrect workspace issue, more details on (https://drone7.rancher.io/rancher/helm/2/3)

2. run `make test-unit` will fail because the testing cases are not up-to-the-date with rancher's comment changes.

**Solution:**
1. The workspace path is required to be set to `$GOPATH/src/k8s.io/helm` according to the helm doc https://docs.helm.sh/developers/#building-helm-tiller . 
And add workspace path `/go/src/k8s.io/helm/ ` to the `.drone.yaml` .

2. Updating the test cases accordingly.

**Related PRs:**
https://github.com/rancher/helm/pull/13#issuecomment-457274887

### CODE REVIEW

**Comment by guangbochen** [comment]
Hi @cjellick @cloudnautique, the previous https://github.com/rancher/helm/pull/13#issuecomment-457274887 CI/CD build fails is because the incorrect workspace issue, can u guys please review this PR and let me know if I need to do anything to address the last failed build, thanks.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/16769

**Comment by cjellick** [comment]
maybe its related to this comment you made
> run make test-unit will fail because the testing cases are not up-to-the-date with rancher's comment changes.

but i dont know what "rancher's comment changes" means

**Comment by cjellick** [comment]
I get it now. Change was introduced in https://github.com/rancher/helm/pull/4
LGTM

**Comment by guangbochen** [comment]
yep, will specify more detailed issue or prs in the description for the next time, thanks.

**Pull request merged**
