### PR TITLE
[v1.31] Helm v3.16.1

### PR DESCRIPTION
**Pull request by krunalhinguu**
### Update

- Add support for K8s `v1.31`
- Add helm `v3.16.1` from upstream and cherry pick rancher specific commits.
- Updated testcase `TestExistingResourceConflict` to match with rancher specific changes

### Releated

- https://github.com/rancher/rancher/issues/46197

### CODE REVIEW

**Review by kinarashah — APPROVED** [review]

**Review by rohitsakala — APPROVED** [review]
LGTM codewise.

**Comment by mallardduck** [comment]
Now that this is merged, for shell image I think I just need to update to use `v3.16.1-rancher1` for building helm?

https://github.com/rancher/shell/blob/ddba4d769b4482f9c349b78132195c768885dde5/hack/make/deps.mk#L2

**Comment by krunalhinguu** [comment]
yes @mallardduck. it is just updating the helm version.

**Comment by krunalhinguu** [comment]
https://github.com/rancher/shell/pull/275 raised the PR. @mallardduck

**Pull request merged**
