### PR TITLE
Add additional label for fore-upgrade resources

### PR DESCRIPTION
**Pull request by guangbochen**
**Problem:**
`helm upgrade` with `--force` option will recreate k8s resources like service if it contains immutable fields, a newly created service will missing the original field like `"io.cattle.field/appId": "xxxx",`, need to bring it back for Rancher.

**Solution:**
add `"io.cattle.field/appId": "xxxx"` to new k8s resource that is re-created helm upgrade `-- force`.

**Issue:**
https://github.com/rancher/rancher/issues/16769

**Related:**
https://github.com/rancher/rancher/pull/17193

### CODE REVIEW

**Comment by guangbochen** [comment]
Hi @StrongMonkey, can u please also review this PR, thanks.

**Comment by StrongMonkey** [comment]
LGTM

**Comment by cjellick** [comment]
AH! https://drone7.rancher.io/rancher/helm/2/3 binary does not compile!

**Comment by guangbochen** [comment]
I will take a look at this @cjellick, thanks.

**Pull request merged**
